{
  "url": "https://api.github.com/repos/DataDog/dd-trace-py/releases/226029270",
  "assets_url": "https://api.github.com/repos/DataDog/dd-trace-py/releases/226029270/assets",
  "upload_url": "https://uploads.github.com/repos/DataDog/dd-trace-py/releases/226029270/assets{?name,label}",
  "html_url": "https://github.com/DataDog/dd-trace-py/releases/tag/v3.9.2",
  "id": 226029270,
  "author": {
    "login": "emmettbutler",
    "id": 723615,
    "node_id": "MDQ6VXNlcjcyMzYxNQ==",
    "avatar_url": "https://avatars.githubusercontent.com/u/723615?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/emmettbutler",
    "html_url": "https://github.com/emmettbutler",
    "followers_url": "https://api.github.com/users/emmettbutler/followers",
    "following_url": "https://api.github.com/users/emmettbutler/following{/other_user}",
    "gists_url": "https://api.github.com/users/emmettbutler/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/emmettbutler/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/emmettbutler/subscriptions",
    "organizations_url": "https://api.github.com/users/emmettbutler/orgs",
    "repos_url": "https://api.github.com/users/emmettbutler/repos",
    "events_url": "https://api.github.com/users/emmettbutler/events{/privacy}",
    "received_events_url": "https://api.github.com/users/emmettbutler/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "node_id": "RE_kwDOA6uE5s4NeO7W",
  "tag_name": "v3.9.2",
  "target_commitish": "3.9",
  "name": "3.9.2",
  "draft": false,
  "prerelease": false,
  "created_at": "2025-06-18T00:38:34Z",
  "published_at": "2025-06-18T00:40:40Z",
  "assets": [

  ],
  "tarball_url": "https://api.github.com/repos/DataDog/dd-trace-py/tarball/v3.9.2",
  "zipball_url": "https://api.github.com/repos/DataDog/dd-trace-py/zipball/v3.9.2",
  "body": "### Bug Fixes\r\n\r\n- This fix resolves an issue in which traced nested generator functions\r\n  had their execution order subtly changed in a way that affected the\r\n  stack unwinding sequence during exception handling. The issue was\r\n  caused by the tracer's use of simple iteration via\r\n  ``for v in g: yield v`` during the wrapping of generator functions where\r\n  full bidrectional communication with the sub-generator via\r\n  ``yield from g`` was appropriate. See PEP380 for an explanation of how\r\n  these two generator uses differ."
}
